name: create-image-chart-url
author: Grégoire Boiron (Graygzou)
description: Create a path of an image based on given data
inputs:
  name-array:
    description: "Array of string to use as axis legends."
    required: true
    default: '[]'
  data-array:
    description: "Array of values to display."
    required: true
    default: '[]'
outputs:
  chart-url:
    description: "Full url using the image-chart API"
    value: ${{ steps.compose-url.outputs.full-url }}
runs:
  using: "composite"
  steps:
    - name: Build URL prefix
      id: url-prefix
      run: |
        prefix="https://image-charts.com/chart?chbh=a&chbr=5&"
        colors="chco="$( printf %s "fdb45c,27c9c2,1869b7" | jq -sRr @uri )
        echo $prefix$colors
        echo "::set-output name=URL::$prefix$colors"
      shell: bash
        
    - name: Build rendering parameters
      id: url-rendering
      run: |
        bounds="chds=a"
        textmarkers="chm="$(printf %s "N,000000,0,,10|N,000000,1,,10|N,000000,2,,10" | jq -sRr @uri )
        margins="chma="$(printf %s "0,0,10,10" | jq -sRr @uri )
        size="chs="$(printf %s "900x600" | jq -sRr @uri )
        type="cht="$(printf %s "bhg" | jq -sRr @uri )
        title="chtt="$(printf %s "Metrics for each solution in chronological order" | jq -sRr @uri )
        visibleAxes="chxt="$(printf %s "y" | jq -sRr @uri )
        
        url="$bounds&$textmarkers&$margins&$size&$type&$title&$visibleAxes"
        echo $url
        echo "::set-output name=URL::$url"
      shell: bash

    - name: Build axis labels
      id: url-axis
      run: |
        axisLabels="chxl="$(printf %s "0:|${{ join(fromJSON(inputs.name-array), '|') }}" | jq -sRr @uri )
        echo $axisLabels
        echo "::set-output name=URL::$axisLabels"
      shell: bash
      
    - name: Build data parameters
      id: url-data
      run: |
        data="chd="$(printf %s "t:${{ join(fromJSON(inputs.data-array), ',') }}" | jq -sRr @uri )
        echo $data
        legends="chdl="$(printf %s "Time (ms)" | jq -sRr @uri )
        echo $legends

        url="$data&$legends"
        echo "::set-output name=URL::$url"
      shell: bash

    - name: Compose the final URL
      id: compose-url
      run: |
        finalurl="${{ steps.url-prefix.outputs.URL }}&${{ steps.url-axis.outputs.URL }}&${{ steps.url-data.outputs.URL }}&${{ steps.url-rendering.outputs.URL }}"
        echo $finalurl
        echo "::set-output name=full-url::$finalurl"
      shell: bash

branding:
  icon: play
  color: blue
